### ISSUE TITLE
Basket appears empty after the declining of an order

### ISSUE THREAD

**Issue by ghost** [AltaPay/magento2#10]
When the user is redirected to the shipping page after the declining of the order, the basket appears empty. Actually I think it's not empty, but it appears empty. I'm sending a screenshot, where you can see that the basket appears empty, but the items are in the Orders Summary section.

Maybe it's a Magento issue, not a plugin issue.

![image](https://user-images.githubusercontent.com/20107467/28115055-afd3bb72-6703-11e7-8fc5-b1076c46b191.png)

**Comment by lb-altapay-com** [comment]
Tested this on 2.1.7, 2.1.8 and 2.1.9. This seems fixed. Also, I see, this as a Magento issue and not a plugin issue.
