### ISSUE TITLE
When doing a partial refund the tax isn't matching

### ISSUE THREAD

**Issue by ghost** [AltaPay/magento2#11]
When doing a partial refund the tax isn't matching. I'm sending a screenshot. In this example, the order line says the tax is 64.17, but next to the refund button the tax is 84.46.

![image](https://user-images.githubusercontent.com/20107467/28115127-039fd862-6704-11e7-9a3b-25a11b34b47d.png)

**Comment by lb-altapay-com** [comment]
This is a general Magento bug, as I see it.

**Comment by BushraAsif** [comment]
Since this is a Magento bug, Please upgrade to the latest version.
