### ISSUE TITLE
Online Refunds

### ISSUE THREAD

**Issue by bobemoe** [AltaPay/magento2#17]
Should it be possible to do an online refund at the moment? 

When creating credit memo there is only a "Refund Offline" button and this does not trigger a refund on the gateway.  I was expecting to see a "Refund" button as well.  Is this functionality expected/planned?  Or have I misconfigured something?

Magento   2.1.9
AltaPay/magento2   0.1.8

**Comment by lb-altapay-com** [comment]
Yes, it should be possible to make a online refund.
If you goto Sales -> Orders.
Click "View" for the order you want to refund.
then click "Invoices" in the "order view" box.
there should be some option for refund.

**Comment by bobemoe** [comment]
Ahha, I was doing: ```Orders -> View -> Credit Memo``` where only the "Refund Offline" button is available.

If I go to ```Invoices -> View -> Credit Memo``` than additional to the "Refund Offline" button is the "Refund" button I was looking for.

Thanks for pointing me in the right direction.

Why is the button missing when creating a Credit Memo from Orders? I guess this could be desired behaviour. If so, feel free to close the issue as I am happy now that it is possible to do a Online Refund.

**Comment by lb-altapay-com** [comment]
This is standard Magento 2. So your idea make sense, but it would require to much maintenance from our side to implement this.
