### ISSUE TITLE
Mapping of Terminals on store-level are ignored 

### ISSUE THREAD

**Issue by it-unoliving** [AltaPay/magento2#18]
I'm currently testing the module on a multi-store magento2 test-environment, using the altapay test gateway.

I've mapped the modules terminal slots to the appropriate backend terminals in default scope, and this works as expected for our main store.
When attempting to assign different backend terminals on store_view scope, nothing changes.
The settings are saved, but they don't seem to have any effect.

The issue only seems to affect the terminal-selection field ("Terminal name"), and the other parameters "Enabled/Disabled" and "Label" both seem to work like intended.

**Comment by sz-altapay-com** [comment]
This issue has been fixed in a newer version. Thank you for pointing out!
