### ISSUE TITLE
"Internal Error" is shown after a declined payment 

### ISSUE THREAD

**Issue by bobemoe** [AltaPay/magento2#19]
The error message is a bit vague. As far as I can see there is also no log of declined payments? We have customers asking what the issue is and we do not know either! I think it is their card has been declined, but we cant find a way to confirm this.

I have tested on the test gateway using the declined card numbers, and just get the "Internal Error" message.  Is this message provided from altapay servers or the extension? Maybe it could read "Card Error" as "Internal Error" suggests a server config error 500.

Is this working as expected, or am I missing some logs or something? Any insights? Thanks :)

**Comment by bobemoe** [comment]
OK, so I've now found in the AltaPay merchant information portal the real error message "Credit card with bin: 371788 is not supported by Valitor. Only Visa or Mastercards is.[54321] "

So can we get this error passed on to the user, either as is, or a bit more user friendly?

**Comment by sz-altapay-com** [comment]
No, such messages should be shown only to the merchant, due to PCI regulations.
