### ISSUE TITLE
Multiple order lines of type handling

### ISSUE THREAD

**Issue by ghost** [AltaPay/magento2#2]
I created an order that contains only one discount. 

The discount was created in the Magento backend (in Marketing > Cart Price Rules).

The resulting order lines contains multiple lines of type handling. Ideally, it should contain
only one line of type handling. More then one line of type handling can exist if there was
multiple discounts applied (multiple coupons applied, for example), but that wasn't the case.
Also, the handling amount must be negative.

Expected order lines:

orderLines[0][description]:	Affirm Water Bottle
orderLines[0][itemId]:	24-UG06
orderLines[0][quantity]:	1.0000
orderLines[0][unitPrice]:	7.0000
orderLines[0][goodsType]:	item
orderLines[1][description]:	Strive Shoulder Pack
orderLines[1][itemId]:	24-MB04
orderLines[1][quantity]:	2.0000
orderLines[1][unitPrice]:	32.0000
orderLines[1][goodsType]:	item
orderLines[2][description]:	Dual Handle Cardio Ball
orderLines[2][itemId]:	24-UG07
orderLines[2][quantity]:	1.0000
orderLines[2][unitPrice]:	12.0000
orderLines[2][goodsType]:	item
**orderLines[3][description]:	Discount
orderLines[3][itemId]:	coupon-id
orderLines[3][quantity]:	1
orderLines[3][unitPrice]:	-9.22
orderLines[3][goodsType]:	handling**
orderLines[4][description]:	flatrate
orderLines[4][itemId]:	flatrate
orderLines[4][quantity]:	1
orderLines[4][unitPrice]:	5.0000
orderLines[4][goodsType]:	shipment

Actual order lines:

orderLines[0][description]:	Affirm Water Bottle
orderLines[0][itemId]:	24-UG06
orderLines[0][quantity]:	1.0000
orderLines[0][unitPrice]:	7.0000
orderLines[0][goodsType]:	item
orderLines[1][description]:	Affirm Water Bottle
orderLines[1][itemId]:	24-UG06
orderLines[1][quantity]:	1
orderLines[1][unitPrice]:	0.7800
orderLines[1][goodsType]:	handling
orderLines[2][description]:	Strive Shoulder Pack
orderLines[2][itemId]:	24-MB04
orderLines[2][quantity]:	2.0000
orderLines[2][unitPrice]:	32.0000
orderLines[2][goodsType]:	item
orderLines[3][description]:	Strive Shoulder Pack
orderLines[3][itemId]:	24-MB04
orderLines[3][quantity]:	1
orderLines[3][unitPrice]:	7.1100
orderLines[3][goodsType]:	handling
orderLines[4][description]:	Dual Handle Cardio Ball
orderLines[4][itemId]:	24-UG07
orderLines[4][quantity]:	1.0000
orderLines[4][unitPrice]:	12.0000
orderLines[4][goodsType]:	item
orderLines[5][description]:	Dual Handle Cardio Ball
orderLines[5][itemId]:	24-UG07
orderLines[5][quantity]:	1
orderLines[5][unitPrice]:	1.3300
orderLines[5][goodsType]:	handling
orderLines[6][description]:	flatrate
orderLines[6][itemId]:	flatrate
orderLines[6][quantity]:	1
orderLines[6][unitPrice]:	5.0000
orderLines[6][goodsType]:	shipment

**Comment by lsv** [comment]
So the description needs to by discount?
I have fixed so the unitprice is -7.11 (minus)

But not tagged yet, its only in master branch

**Comment by ghost** [comment]
The description is by discount. But the important thing is that each itemId must be unique.

**Comment by lsv** [comment]
Item id is the same as the product id.
Discount can also be on products (when the discount is made via cart rule or catalog rule) not just coupons

**Comment by ghost** [comment]
I think if the discount is on the product, you can save the value with discount in the unitPrice field (no need to create a handling line).

But if it's a coupon, you can create a handling line for the coupon.

**Comment by lsv** [comment]
So if a product has a discount (created from a cart rule or catalog 
rule) it should not be a handling orderline?


Den 04-01-2017 kl. 14:58 skrev et-altapay-com:

**Comment by lsv** [comment]
Also, special price on a product does not create a handling orderline



Den 04-01-2017 kl. 15:00 skrev Martin:

**Comment by ghost** [comment]
> So if a product has a discount (created from a cart rule or catalog
> rule) it should not be a handling orderline?

No, it's not necessary.

> Also, special price on a product does not create a handling orderline

Ok.
