### ISSUE TITLE
Notice: Undefined variable: _order

### ISSUE THREAD

**Issue by AleksLi** [AltaPay/magento2#22]
I have 0.5.0 altapay/magento2-payment module installed via the composer without any overridden files on my project. I've checked the latest version of your module (which is 0.14.0 on this moment) and found the same code for the form.phtml template.

I've got this message trying to reach any of the Shipment View page.
I'm attaching the screenshot of the message.
![shipment error formphtml](https://user-images.githubusercontent.com/10618641/74521904-7cd06e80-4f1a-11ea-8dce-4936014fad2f.png)

### Reproducing
1. Create any order -> create shipment
2. Go to admin panel Sales-> Shipment 
3. Pick any of the created shipments.

You will see the message only in developer mode. In production mode you will get just a page without content.

**Comment by BushraAsif** [comment]
This has been resolved in the latest version.
