### ISSUE TITLE
ePayment not captured in Magento backend

### ISSUE THREAD

**Issue by ghost** [AltaPay/magento2#5]
Another problem occurs when trying to use ePayments. It's possible to create an order without problems, but if I try to capture the order in the Magento backend an error occurs. That makes sense, because an ePayment is captured up front. The problem is that it's not possible to create an Invoice for an ePayment. Thus, it's also not possible to do a refund.

**Comment by ghost** [comment]
According to Martin:

You need to set "Auto capture" to yes when using a payment that gets captured immediately

**Comment by ghost** [comment]
Danny comment:

Some payment methods do no support authorize only. The way the gateway handles this is that a merchant who has their setup set to authorize only and using a payment method not support authorizations, the gateway will automatically change the payment type to paymentAndCapture.

This should be something that the plugin should react on accordingly since this is an abstraction between payment methods that the merchant should not need to be concerned about (and will in many instances result in them misconfiguring Magento due to them not understanding or forgetting this).
I believe the Magento 1 plugin takes this correctly into consideration.

**Comment by ghost** [comment]
At the moment, use "Auto capture".

When auto capture is set, it will change to Magento to force auto capture - which it does BEFORE the payment is actually activated, so its not possible to not set it.

**Is this a Magento limitation or a limitation of the implementation?**

**Comment by lsv** [comment]
Im not sure - As Magento are not documented at all, its quite hard to say whats excactly needs to be done, or if its actual possible.

Though in Denmark its not allowed to capture money before the product has actually being shipped

**Comment by lb-altapay-com** [comment]
I can see, there is no capture state. So there is no state, to tell, if a payment is reserved or capture, so I don't think this bug is relevant.
