### ISSUE TITLE
Support for Magento >2.1.3?

### ISSUE THREAD

**Issue by bobemoe** [AltaPay/magento2#8]
I am setting up a new Magento site using the latest Magento2.1.6 but this extension requires magento <=2.1.3

Will I have to downgrade magento or is there support for the latest?

**Comment by bobemoe** [comment]
2.1.7 is now out. What are my option here about staying up to date? Or am I stuck with PayPal?

**Comment by ghost** [comment]
We didn't test the plugin using versions newer than 2.1.3, but we are planning that.

**Comment by ghost** [comment]
The last release of the plugin will work correctly on Magento 2.1.7. Nonetheless, it is still on beta mode.

**Comment by bobemoe** [comment]
Thanks for this.  It now installs, we will give it a thorough test and report back any issues. Thanks again.
