### ISSUE TITLE
Declined order is not changed to Canceled

### ISSUE THREAD

**Issue by ghost** [AltaPay/magento2#9]
When an order is declined by the gateway, or canceled by the customer, its status in the Magento backend should change to 'Canceled'.

When an order is declined, the customer is redirected to the shipping page, and can try to purchase
again using another payment method or another credit card. When he tries to purchase again, a new order is being created. This is alright.The problem is that the previous order (the declined one) wasn't canceled in Magento.

**Comment by lb-altapay-com** [comment]
There doesn't seem to be a Canceled state in Magento. I can see, that a declied transaction would have the status pending payment. So there is an indication, that the payment hasn't been complete and that is fine.
